# Base de données    projet151
# Username           projet151
# Password           projet151
USE projet151;

# Données de la table t_genre
INSERT INTO t_genre (name) VALUES 
('Dictionnaire'),
('Magazine'),
('Roman & Fictions'),
('Bande Dessinée & Mangas'),
('Manuel scolaire'),
('Essai'),
('Polar'),
('Autre'),
('Religions, spiritualité'),
('Humour'),
('Fantastique'),
('Théâtre'),
('Nouvelle'),
('Horreur'), 
('Science-fiction'),
('Poésie'),
('dont vous êtes le héro'),
('Extraits'),
('Recueil de planches'),
('Atlas'),
('Brochure'),
('Documents & Sciences'),
('Mode d\'emploi'),
('Cuisine'),
('Polycopié'),
('Manuel'),
('Revue'),
('Abécédaire'),
('Biographie'),
('Annuaire'),
('Esotérisme'),
('Lexique'),
('Loisirs'),
('Sport');

INSERT INTO t_book (title, overview, author_sex, author_name, author_fname, year, price, img_cover, edition, logistic_qnt, FK_genre) VALUES 
('Une brève histoire du temps','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Navigation d\'Ulysse','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Feu Mathias Pascal','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Fumée rouge','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Voyage au bout de la nuit','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Le guide Marabout du Judo','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,2),
('Métapsychologie','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Se','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,2),
('Tolérance zéro','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Le meilleur des mondes','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Bel-Ami','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Les oreilles rouges','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('La chute','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Français-Allemand','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,2),
('Alex','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('The joy luck club','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Le cœur conscient','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('La part du vent','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Jonathan Livingston Seagull','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Educating Rita','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Lies of silence','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Nuits d\'enfer','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Enemies','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Maria, fille de Flandre','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Aphrodite','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Le pot au noir','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Le grand Meaulnes','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Corps et âmes','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('La Bible','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('La crevasse des maquisards','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Tristan et Iseult','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Le gambit des étoiles','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Stamps & stories','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,2),
('Skinwalkers','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('The Christmas books','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('A Christmas Carol','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('La dixième prophétie','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('L\'homme qui rétrécit','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Histoires extraordinaires','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Nouvelles histoires extraordinaires','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('La pureté dangereuse','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Zazie dans le métro','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('La visite de la vieille dame','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Le Colonel Chabert','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1),
('Phèdre','overview', 'M', 'David', 'Miranda', 2014, 25.50, 'dsdasdsadasd', 'edition', 15 ,1);
